language: objective-c
osx_image: xcode9.1

cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem install cocoapods
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean build test
     -workspace Example/RxCocoa-Texture.xcworkspace 
     -scheme RxCocoa-Texture-Example 
     -sdk iphonesimulator
     -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0'
     -configuration Debug
     -enableCodeCoverage YES
     CODE_SIGNING_REQUIRED=NO | xcpretty